### ISSUE TITLE
Arm64 support

### ISSUE THREAD

**Issue by TQMatvey** [flipperdevices/flipperzero-toolchain#3]
Feature request: Make arm64 toolchain so it would be possible compile and work on firmware on SBCs like raspberry pi, tablets, even phones

**Comment by krak3n77** [comment]
+1 this.

**Comment by bananu7** [comment]
+1, I would love to run this on my phone, but `ufbt` complained about lack of ARM toolchain setup. I briefly looked at what would be necessary to get it to work and it _seems_ like a straightforward change, so I might try making a stab at this.

**Comment by krak3n77** [comment]
> +1, I would love to run this on my phone, but `ufbt` complained about lack of ARM toolchain setup. I briefly looked at what would be necessary to get it to work and it _seems_ like a straightforward change, so I might try making a stab at this.

https://github.com/qqmajikpp/FBT-AARCH64 isn't an official solution, but it works fine for me in termux.

**Comment by drunkbatya** [comment]
Yeah, we're planning to add aarch64 support together with GCC 12 in the next release

**Comment by drunkbatya** [comment]
Aarch64 linux support was added to the latest toolchain release, @bananu7 @detectingdragon77 @TQMatvey can you check it?

```bash
# on aarch64 linux platform
git clone https://github.com/flipperdevices/flipperzero-firmware.git
cd flipperzero-firmware
git checkout hedger/toolchain-tests
./fbt
```

**Comment by bananu7** [comment]
Perfect timing :D I'll check it at the earliest convenience

**Comment by krak3n77** [comment]
Compiled successfully in termux Debian proot here.

**Comment by TQMatvey** [comment]
Thanks! Can confirm, it's working on Khadas VIM 4 (aarch64). Closing the issue as resolved.

**Comment by bananu7** [comment]
Was ufbt updated to reflect that as well? I am getting the old message of unsupported arch on 0.2.5 still.

I've tried this repo and with 
```
git checkout hedger/toolchain-tests
./fbt
```
I'm getting
```
./fbt: 8: getconf: not found
```

I guess that's not strictly ARM, that's a missing glibc?

**Comment by TQMatvey** [comment]
sooo when will this be merged into main?
